package:
  name: transpiration_estimation_algorithm
  version: "0.02"

source:
  git_rev: 0.02
  git_url: https://github.com/jnelson18/TranspirationEstimationAlgorithm.git

requirements:
  build:
    - python
    - setuptools
    - scipy
    - numpy
    - xarray

  run:
    - python

test:
  imports:
    - TranspirationEstimationAlgorithm

about:
  home: https://github.com/jnelson18/TranspirationEstimationAlgorithm
  license: GPL-3.0
  license_file: LICENSE
